//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcFirmaCagri.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTasks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblTasks()
        {
            this.TblTaskDetails = new HashSet<TblTaskDetails>();
        }
    
        public int ID { get; set; }
        public Nullable<int> TaskGiver { get; set; }
        public Nullable<int> TaskTaker { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual TblStaffs TblStaffs { get; set; }
        public virtual TblStaffs TblStaffs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblTaskDetails> TblTaskDetails { get; set; }
    }
}
